### ISSUE TITLE
Several tags on one note?

### ISSUE THREAD

**Issue by altaheer** [HyeonseoNam/auto-classifier#14]
Hello, Im very amateur in coding, I just hope to understand coding.
Ive tried to write the prompt in any way possible to get one thing:
Right now it will just add one tag, I want basically chatgpt to find as many possible relevant tags and add several to the note. How can I do that?

**Comment by jenpritchard** [comment]
same! What I need is:
* First, return **all** relevant tags from the ones that already exist in the vault (no matter how many), and then...
* multiple new tags (maybe have a setting for how many to return)
* Ask for confirmation for which tags look good before adding them 

Here's an example:
1. I set my "number to return" as 5.
2. From an existing list of 100 tags, the AI determines that there are 6 that apply.
3. The AI then suggests 5 new tags
4. A popup should present the first 6 and the second 5 (so a total of 11), indicating which are old or new, and allow me to reject any of them before adding them.

**Comment by mattjoyce** [comment]
I came to ask for this, and perhaps contribute if I can.
My preference would be quite simple, pick the next tags from the reference and generate n new tags.
Allow the prompt to be editable, so we just need to process a json response with multiple tags.

**Comment by HyeonseoNam** [comment]
Hi all, thanks to @rtuszik, you can now use multiple tags on version 1.2.0 !
