### ISSUE TITLE
[ feature request ] assets tags

### ISSUE THREAD

**Issue by miztizm** [HyeonseoNam/auto-classifier#16]
Is it feasible to configure this plugin to operate with various types of assets, including images, PDFs, and videos? Specifically, I'm interested in tagging these media assets based on the information derived from their filenames. Thank you.

**Comment by gravityfargo** [comment]
What you're asking for is a limitation of obsidian. There's many reddit posts and obsidian forum posts on this topic. Embedding the media in a markdown file and applying the tag there seems to be on only approach.
