### ISSUE TITLE
FR: Link Output

### ISSUE THREAD

**Issue by brimwats** [HyeonseoNam/auto-classifier#2]
Re #1 , I would like to have chatgpt fetch me wikidata classifications but to do so in a markdown link format, not in the frontmatter; could we have a setting for output in [[links]] and [links]() and not just tags?

**Comment by HyeonseoNam** [comment]
Yeah, that's a good suggestion. Could you give me more details about how you want to use? Your usecase is selected area -> [[links]] in current cursor?

**Comment by brimwats** [comment]
of course! I am in Library and Informatio n Science so I use BT NT RT, like this:

![image](https://user-images.githubusercontent.com/73113656/229169963-f06da035-2ce2-4605-a4a3-f1270b63873b.png)

but for the wikidata example, say I am writing about penguins, and I'd like it to get wikidata items for penguins, it would look like this:

Wikidata: [penguin (Q9147)](https://www.wikidata.org/wiki/Q9147)

Ideally, it could be more advanced and pick up other things, like:

[instance of](https://www.wikidata.org/wiki/Property:P31): [taxon](https://www.wikidata.org/wiki/Q16521)
[parent taxon](https://www.wikidata.org/wiki/Property:P171): [Sphenisciformes](https://www.wikidata.org/wiki/Q12198609)
[taxon range](https://www.wikidata.org/wiki/Property:P9714): [Brazil](https://www.wikidata.org/wiki/Q155)

etc

**Comment by HyeonseoNam** [comment]
Hey, I updated to version 1.1.0 including [[link]] output type based on your feedback. I'm really glad to have implemented some meaningful changes. Thank you so much for sharing your feedback !!
