### ISSUE TITLE
Output format error

### ISSUE THREAD

**Issue by aarontimo** [HyeonseoNam/auto-classifier#20]
HI @HyeonseoNam.

Thanks for the great plugin.

I was trying to process a note using autoclassifier → `classify tag from Note Content`, and I received the following error:

![image](https://github.com/HyeonseoNam/auto-classifier/assets/12866978/a6702e5c-de6e-4697-988a-156faa3e527e)

Many thanks 
Aaron

**Comment by gomgom50** [comment]
I'm having the same issue now.

**Comment by HyeonseoNam** [comment]
Hi, @aarontimo and @gomgom50. Thanks to @gravityfargo, the error has been resolved. Thank you for your participation !
