### ISSUE TITLE
Error on ChatGPT API Key 

### ISSUE THREAD

**Issue by SunProg** [HyeonseoNam/auto-classifier#22]
<img width="483" alt="image" src="https://github.com/HyeonseoNam/auto-classifier/assets/24718003/153392cd-90be-4ec4-82cf-9d4cdcf05cb2">

While setting API, even if the API key is right and I had double checked it with other plugins, the plugin said that the error occurred.

I try with restarting the plugin and obsidian several times. It continually failed to set the API.

**Comment by HyeonseoNam** [comment]
Hi, @SunProg! Try this #19.

**Comment by SunProg** [comment]
@HyeonseoNam Sorry for asking again, I am not sure how could I do with #19, since I installed the plugin through community plugins store.

**Comment by HyeonseoNam** [comment]
@SunProg, Sorry. I should have mentioned #9, not #19. Are you sure your billing is working properly?

**Comment by HyeonseoNam** [comment]
If the error continues, please comment again.
