### ISSUE TITLE
[Feature Request] Allow related files

### ISSUE THREAD

**Issue by anandbhaskaran** [HyeonseoNam/auto-classifier#23]
We could find related files from the content and populate the related files similar to tags.

**Comment by HyeonseoNam** [comment]
Hi @anandbhaskaran, 

Finding related files or content for notes would indeed be a valuable feature. However, implementing such a feature would likely involve complex methods like embeddings or tokenization, which are beyond the current scope of this plugin. 

Sincerely appreciate your opinion and will keep it in mind for future improvements. Thank you.
