### ISSUE TITLE
option to recommend more tags

### ISSUE THREAD

**Issue by adrian-goe** [HyeonseoNam/auto-classifier#3]
Hi,
My understanding is that it is only possible to select tags from previously specified tags. 
My obsidian is currently quite empty, as I am relatively new to this. Therefore, it would be quite practical if it were possible for new tags to be suggested.

**Comment by HyeonseoNam** [comment]
Hi @adrian-goe, 

You can choose your `Reference type` as `Manual tags` in the setting tab. You can set the tags what you want manually, or remove {{reference}} from the `Custom Prompt Template` and set your own command for ChatGPT.

By the way, I just updated this plugin to version 1.1.0. I recommend trying these out after the update ! Thanks.
