### ISSUE TITLE
 no input data

### ISSUE THREAD

**Issue by Kmfernan5** [HyeonseoNam/auto-classifier#5]
The message "No input data" keeps appearing at the top repeatedly.

**Comment by HyeonseoNam** [comment]
Hi @Kmfernan5, 

Do you mean that one "no input data" message is floating still? Or multiple messages repeatedly overlap?

Also, more information is needed. Please give me about these things.
- which of the following commands you used?
   - `Classify tag from Note title`
   - `Classify tag from Note FrontMatter`
   - `Classify tag from Note Content`
   - `Classify tag from Selected Area`

- what was the input text when you run the command?
- Could you capture the setting tab (Settings > Auto classifier)?
