### ISSUE TITLE
Multiple tags

### ISSUE THREAD

**Issue by sam1am** [HyeonseoNam/auto-classifier#6]
Ideally I would like to add up to half a dozen tags at once. Is this possible or even with a custom prompt is it always expecting a single tag? 

I tried this: 
<img width="817" alt="Screenshot 2023-05-31 at 10 16 45 AM" src="https://github.com/HyeonseoNam/auto-classifier/assets/127555/df452173-3c68-44f3-827d-afe12565fb7e">

But the output I get is simply 
```
#[
```

**Comment by mazoviansocioeconomist** [comment]
After some careful massaging, its possible to get GPT3 to generate multiple tags at once using this script:
You are a JSON answer bot. Don't answer other words.

Please use Dewey Decimal Classification (DDC) to classify this content with up to five tags if it makes sense to do so. Do not include duplicates. From these tags, determine the 'Updated Categories' that are capitalised in Pascal Case and have had blank spaces removed:
"""
{{input}}
"""
Answer format is JSON {reliability:0~1, output:"[ddc_number]:UpdatedCategory,[ddc_number2]:UpdatedCategory2,[ddc_number3]:UpdatedCategory3,[ddc_number4]:UpdatedCategory4,[ddc_number5]:UpdatedCategory5"}. 
Even if you are not sure, qualify the reliability and select one. 
Remove the blank spaces between words in the output.

But the plugin itself only takes the first one and drops the rest.
