### ISSUE TITLE
Test API call = Error: API is not working 

### ISSUE THREAD

**Issue by cole21771** [HyeonseoNam/auto-classifier#9]
I've tried multiple API keys and it always seems to fail with the same error and no details. Did they change the API response maybe and this needs to be updated to work with it?

**Comment by HyeonseoNam** [comment]
Hi @cole21771 !

Some people have experienced the same issue where their payment method was not properly registered in Payment. If the payment information is initialized or not entered, the API will not work even if you have API keys. 

Please check here at https://platform.openai.com/account/billing/overview first, and if the problem persists, please leave a screenshot (the error what you see) here.

**Comment by cole21771** [comment]
Thanks for the quick response! Yup, that was the issue! 

You should add a check for the error message about billing and change the message to the user. Or log out the actual error from chat gpt somewhere accessible instead of throwing it away so it's clear what the issue is.

**Comment by HyeonseoNam** [comment]
It's a relief that the problem has been caught.

Yes, I'm considering ways to track errors as they occur. This case will be a good reference. Thank you!
